### DISCUSSION TITLE
Added support for AWS logging

### DISCUSSION THREAD

**Discussion by jayjb** [thinkst/canarytokens-docker#165] [Announcements]
We have added support for AWS logging. If you use the new `docker-compose-aws-logging*.yml` file in your `docker-compose` flow, it will automatically try send the logs from your server to AWS Cloudwatch. This is what it looks like in the compose file:
```
    logging:
      driver: awslogs
      options:
        awslogs-region: ${CANARYTOKENS_LOGGING_REGION:-eu-west-1}
        awslogs-group: ${CANARYTOKENS_LOGGING_GROUP:-canarytokens}
        awslogs-stream: frontend
```

You'll notice that we have included two new environment variables too. These are
- `CANARYTOKENS_LOGGING_REGION` : the region in which you would like the logs sent in CloudWatch (the default is `eu-west-1`)
- `CANARYTOKENS_LOGGING_GROUP` : the log group name you would like the logs sent to in CloudWatch (the default is `canarytokens`)

You can override these by:
1. Go into your `canarytokens-docker` repo.
2. Create the `.env` file and add the required environment variables you would like to override:
```
~/canarytokens-docker $ vi .env
CANARYTOKENS_LOGGING_REGION=us-east-1
CANARYTOKENS_LOGGING_GROUP=canarytokens-prod
```
3. Restart your Canarytokens server:
```
~/canarytokens-docker $ docker compose -f <compose file you are using> up
```
