### ISSUE TITLE
HTML alert emails, log files and local time...

### ISSUE THREAD

**Issue by jeffshead** [thinkst/canarytokens-docker#115]
**Background info:**
I have successfully installed canarytokens-docker directly on an AlmaLinux 8.6 VPS and I have installed it on another AlmaLinux 8.6 VPS by using stacks in Portainer, behind NGINX Proxy Manager. In both cases, everything seems to be fully working.

**Question 1:**
I noticed email alerts coming from the public canary tokens server (canarytokens.org) are HTML formatted wheras the emails I recieve from my self-hosted server (using SMTP) are in plain text. Is there a setting or an environment variable that can be used to switch to HTML emails?

**Question 2:**
I do not have a **logs** directory nor any log files in the **canarytoken-docker** directory but I do have a working **uploads** directory. Is this normal? In Portainer, I do see that a volume (/var/lib/docker/volumes/canarytokens-docker_log-volume/) was created.

**Question 3:**
Is it possible to use localtime for everything (logs, nginx, email alerts, etc) instead of UTC time? I have tried adding `- "/etc/localtime:/etc/localtime:ro"` to the various `volumes:` in my stack but it does not work and doing so seems to cause issues when building.

**Question 4:**
I created a Custom Web Image Bug and added it to a webpage which is hosted on another server. I used `<img>` tags. It works but it takes about 15 seconds for the image to load. Any ideas as to why it takes so long? I don't believe this has anything to do with the physical servers systems resources. As a test, I used the same image and created an image token on canarytokens.org. The image from canarytokens.org loads in about three seconds. I don't know where to begin troubleshooting this one.

Below is my Portainer stack:
...
```
version: '3'
services:
  redis:
    restart: always
    image: redis
    volumes:   
    - /dir1/dir2/canarytokens-docker/data:/data/
    container_name: redis
    command: redis-server --appendonly yes --protected-mode no --save 60 1
  frontend:
    restart: always
    build: /dir1/dir2/canarytokens-docker/canarytokens/
    image: thinkst/canarytokens
    links:
     - redis
    environment:
      - CANARY_DOMAINS=sub1.example.com
      - CANARY_NXDOMAINS=sub2.example.com
      - CANARY_PUBLIC_IP=1.2.3.4
      - CANARY_WG_PRIVATE_KEY_SEED=sadfhjdEXAMPLEHahjsfGFsadjhf=
      #CANARY_GOOGLE_API_KEY=
      - CANARY_WEB_IMAGE_UPLOAD_PATH=/uploads
      #Enter number so 1024*1024*10 = 10485760
      - CANARY_MAX_UPLOAD_SIZE=10485760
      - LOG_FILE=frontend.log
    volumes:  
    - /dir1/dir2/canarytokens-docker/uploads:/uploads/
    - log-volume:/logs
    container_name: frontend
    command: bash -c "rm -f frontend.pid; twistd -noy frontend.tac --pidfile=frontend.pid"
  switchboard:
    build: /dir1/dir2/canarytokens-docker/canarytokens/
    restart: always
    image: thinkst/canarytokens
    ports:
     - "1.2.3.4:53:53/tcp"
     - "1.2.3.4:53:53/udp"
     - "25:25"
     - "127.0.0.1:3306:3306"
     - "6443:6443"
     - "51820:51820/udp"
    links:
     - redis
    environment:
      - CANARY_NXDOMAINS=sub2.example.com
      #CANARY_MAILGUN_DOMAIN_NAME=
      #CANARY_MAILGUN_API_KEY=
      #CANARY_MANDRILL_API_KEY=
      #CANARY_SENDGRID_API_KEY=
      - CANARY_PUBLIC_IP=1.2.3.4
      - CANARY_SMTP_SERVER=mail.example.com
      - CANARY_SMTP_PORT=587
      - CANARY_SMTP_USERNAME=user@example.com
      - CANARY_SMTP_PASSWORD=examplepassword
      - CANARY_PUBLIC_DOMAIN=sub1.example.com
      - CANARY_ALERT_EMAIL_FROM_ADDRESS=user@example.com
      - CANARY_ALERT_EMAIL_FROM_DISPLAY="Canary Tokens"
      - CANARY_ALERT_EMAIL_SUBJECT="Canary Token Alert"
      - CANARY_WG_PRIVATE_KEY_SEED=sdf84hjdsc67234hjEXAMPLEsdg546gf=
      #CANARY_IPINFO_API_KEY=
      - CANARY_TOKEN_RETURN=fortune
      - CANARY_WEB_IMAGE_UPLOAD_PATH=/uploads
      - LOG_FILE=switchboard.log
      # Default protocol to use in notification links. If you don't use LetsEncrypt, set to http
      - PROTOCOL=https
      - ERROR_LOG_WEBHOOK=

    volumes_from:
    - frontend
    container_name: switchboard
    command: bash -c "rm -f switchboard.pid; twistd -noy switchboard.tac --pidfile=switchboard.pid"
  nginx:
    restart: always
    image: thinkst/canarytokens_nginx
    build: /dir1/dir2/canarytokens-docker/nginx/
    ports:
     - "127.0.0.1:6545:80"
    links:
     - frontend
     - switchboard
    container_name: nginx
    command: /usr/sbin/nginx -c /etc/nginx/nginx.conf -g "daemon off;"
volumes:
  log-volume:
networks:
  default:
    name: example-network
    external: true
```
...
