### ISSUE TITLE
Remove requirement to both inject environment variables as well as .env files

### ISSUE THREAD

**Issue by colin-stubbs** [thinkst/canarytokens-docker#191]
**Is your feature request related to a problem? Please describe.**

The need to define both environment variables taken from frontend/switchboard .env files AS well as injecting those files so that the canarytokens python code can re-read the files... is kinda wild, weird and counter to containerisation.

Given that the same image is being used for both frontend and switchboard, why not just throw the same set of env variables at both incantations?

**Describe the solution you'd like**

Zero requirement should existe to inject either frontend.env or switchboard.env.

Sane defaults should be loaded, and env variables should override them if set, which then allows environment variables to be defined in one place in a compose file or otherwise managed via whatever containerisation platform is in use to initialise the stack/pod/group of containers.

**Describe alternatives you've considered**

Here's my hack around for the current clunk that is both env variables and file as volume injection, nothing more than dumping a sub-set of environment variables into the files that the python code expects to read.

This feels unnecessary at best and a lot of expletives at worst.

```

services:
  canarytokens-frontend:
    image: thinkst/canarytokens:latest
    command: bash -c "cd frontend; env | grep ^CANARY_ > ../frontend/frontend.env; cp ../frontend/frontend.env ../switchboard/switchboard.env; poetry run python -m uvicorn app:app --host 0.0.0.0 --port 8082"
    restart: unless-stopped
    environment:
      CANARY_ALERT_EMAIL_FROM_ADDRESS: ${CANARY_ALERT_EMAIL_FROM_ADDRESS:-do-not-reply@your.domain.tld}
      CANARY_ALERT_EMAIL_FROM_DISPLAY: ${CANARY_ALERT_EMAIL_FROM_DISPLAY:-Canary Tokens}
      CANARY_ALERT_EMAIL_SUBJECT: ${CANARY_ALERT_EMAIL_SUBJECT:-Canary Token Triggered}
      CANARY_DOMAINS: ${CANARY_DOMAINS:-localhost,127.0.0.1}
      CANARY_FORCE_HTTPS: ${CANARY_FORCE_HTTPS:-False}
      CANARY_FRONTEND_LOG_COUNT: ${CANARY_FRONTEND_LOG_COUNT:-10}
      CANARY_FRONTEND_LOG_SIZE: ${CANARY_FRONTEND_LOG_SIZE:-10485760}
      # CANARY_GOOGLE_API_KEY: ${CANARY_GOOGLE_API_KEY:-} 
      # CANARY_IPINFO_API_KEY: ${CANARY_IPINFO_API_KEY:-}
      # CANARY_MAILGUN_API_KEY: ${CANARY_MAILGUN_API_KEY:-}
      # CANARY_MAILGUN_DOMAIN_NAME: ${CANARY_MAILGUN_DOMAIN_NAME:-}
      # CANARY_MANDRILL_API_KEY: ${CANARY_MANDRILL_API_KEY:-}
      CANARY_MAX_ALERTS_PER_MINUTE: ${CANARY_MAX_ALERTS_PER_MINUTE:-1000}
      CANARY_MAX_UPLOAD_SIZE: ${CANARY_MAX_UPLOAD_SIZE:-10485760}
      CANARY_NXDOMAINS: ${CANARY_NXDOMAINS:-nx.127.0.0.1,nx.localhost}
      CANARY_PUBLIC_DOMAIN: ${CANARY_PUBLIC_DOMAIN:-canarytokens.localhost}
      CANARY_PUBLIC_IP: ${CANARY_PUBLIC_IP:-127.0.0.1}
      CANARY_REAL_IP_HEADER: ${CANARY_REAL_IP_HEADER:-x-real-ip}
      CANARY_REDIS_DB: ${CANARY_REDIS_DB:-0}
      CANARY_REDIS_HOST: ${CANARY_REDIS_HOST:-redis}
      CANARY_REDIS_PORT: ${CANARY_REDIS_PORT:-6379}
      CANARY_SENDGRID_API_KEY: ${CANARY_SENDGRID_API_KEY:-CHANGE_ME}
      CANARY_SENDGRID_SANDBOX_MODE: ${CANARY_SENDGRID_SANDBOX_MODE:-True}
      # CANARY_SENTRY_DSN: ${CANARY_SENTRY_DSN:-}
      # CANARY_SENTRY_ENABLE: ${CANARY_SENTRY_ENABLE:-False}
      # CANARY_SENTRY_ENVIRONMENT: ${CANARY_SENTRY_ENVIRONMENT:-local}
      # CANARY_SMTP_PASSWORD: ${CANARY_SMTP_PASSWORD:-}
      # CANARY_SMTP_PORT: ${CANARY_SMTP_PORT:-}
      # CANARY_SMTP_SERVER: ${CANARY_SMTP_SERVER:-}
      # CANARY_SMTP_USERNAME: ${CANARY_SMTP_USERNAME:-}
      CANARY_SWITCHBOARD_LOG_COUNT: ${CANARY_SWITCHBOARD_LOG_COUNT:-20}
      CANARY_SWITCHBOARD_LOG_SIZE: ${CANARY_SWITCHBOARD_LOG_SIZE:-500000000}
      CANARY_SWITCHBOARD_SCHEME: ${CANARY_SWITCHBOARD_SCHEME:-http}
      CANARY_TOKEN_RETURN: ${CANARY_TOKEN_RETURN:-gif}
      CANARY_USING_NGINX: ${CANARY_USING_NGINX:-False}
      CANARY_WEB_IMAGE_UPLOAD_PATH: ${CANARY_WEB_IMAGE_UPLOAD_PATH:-/uploads}
      CANARY_WG_PRIVATE_KEY_SEED: ${CANARY_WG_PRIVATE_KEY_SEED:-vk/GD+frlhve/hDTTSUvqpQ/WsQtioKAri0Rt5mg7dw=}

      # ERROR_LOG_WEBHOOK: ${ERROR_LOG_WEBHOOK:-}
      LOG_FILE: ${LOG_FILE:-frontend.log}
    volumes:
      - logs:/logs
      - uploads:/uploads
    ports:
     - "8082:8082"

  canarytokens-switchboard:
    image: thinkst/canarytokens:latest
    command: bash -c "cd switchboard; rm -f switchboard.pid; env | grep ^CANARY_ > ../frontend/frontend.env; cp ../frontend/frontend.env ../switchboard/switchboard.env; poetry run twistd -noy switchboard.tac --pidfile=switchboard.pid"
    restart: unless-stopped
    environment:
      CANARY_ALERT_EMAIL_FROM_ADDRESS: ${CANARY_ALERT_EMAIL_FROM_ADDRESS:-do-not-reply@your.domain.tld}
      CANARY_ALERT_EMAIL_FROM_DISPLAY: ${CANARY_ALERT_EMAIL_FROM_DISPLAY:-Canary Tokens}
      CANARY_ALERT_EMAIL_SUBJECT: ${CANARY_ALERT_EMAIL_SUBJECT:-Canary Token Triggered}
      CANARY_DOMAINS: ${CANARY_DOMAINS:-localhost,127.0.0.1}
      CANARY_FORCE_HTTPS: ${CANARY_FORCE_HTTPS:-False}
      CANARY_FRONTEND_LOG_COUNT: ${CANARY_FRONTEND_LOG_COUNT:-10}
      CANARY_FRONTEND_LOG_SIZE: ${CANARY_FRONTEND_LOG_SIZE:-10485760}
      # CANARY_GOOGLE_API_KEY: ${CANARY_GOOGLE_API_KEY:-} 
      # CANARY_IPINFO_API_KEY: ${CANARY_IPINFO_API_KEY:-}
      # CANARY_MAILGUN_API_KEY: ${CANARY_MAILGUN_API_KEY:-}
      # CANARY_MAILGUN_DOMAIN_NAME: ${CANARY_MAILGUN_DOMAIN_NAME:-}
      # CANARY_MANDRILL_API_KEY: ${CANARY_MANDRILL_API_KEY:-}
      CANARY_MAX_ALERTS_PER_MINUTE: ${CANARY_MAX_ALERTS_PER_MINUTE:-1000}
      CANARY_MAX_UPLOAD_SIZE: ${CANARY_MAX_UPLOAD_SIZE:-10485760}
      CANARY_NXDOMAINS: ${CANARY_NXDOMAINS:-nx.127.0.0.1,nx.localhost}
      CANARY_PUBLIC_DOMAIN: ${CANARY_PUBLIC_DOMAIN:-canarytokens.localhost}
      CANARY_PUBLIC_IP: ${CANARY_PUBLIC_IP:-127.0.0.1}
      CANARY_REAL_IP_HEADER: ${CANARY_REAL_IP_HEADER:-x-real-ip}
      CANARY_REDIS_DB: ${CANARY_REDIS_DB:-0}
      CANARY_REDIS_HOST: ${CANARY_REDIS_HOST:-redis}
      CANARY_REDIS_PORT: ${CANARY_REDIS_PORT:-6379}
      CANARY_SENDGRID_API_KEY: ${CANARY_SENDGRID_API_KEY:-CHANGE_ME}
      CANARY_SENDGRID_SANDBOX_MODE: ${CANARY_SENDGRID_SANDBOX_MODE:-True}
      # CANARY_SENTRY_DSN: ${CANARY_SENTRY_DSN:-}
      # CANARY_SENTRY_ENABLE: ${CANARY_SENTRY_ENABLE:-False}
      # CANARY_SENTRY_ENVIRONMENT: ${CANARY_SENTRY_ENVIRONMENT:-local}
      # CANARY_SMTP_PASSWORD: ${CANARY_SMTP_PASSWORD:-}
      # CANARY_SMTP_PORT: ${CANARY_SMTP_PORT:-}
      # CANARY_SMTP_SERVER: ${CANARY_SMTP_SERVER:-}
      # CANARY_SMTP_USERNAME: ${CANARY_SMTP_USERNAME:-}
      CANARY_SWITCHBOARD_LOG_COUNT: ${CANARY_SWITCHBOARD_LOG_COUNT:-20}
      CANARY_SWITCHBOARD_LOG_SIZE: ${CANARY_SWITCHBOARD_LOG_SIZE:-500000000}
      CANARY_SWITCHBOARD_SCHEME: ${CANARY_SWITCHBOARD_SCHEME:-http}
      CANARY_TOKEN_RETURN: ${CANARY_TOKEN_RETURN:-gif}
      CANARY_USING_NGINX: ${CANARY_USING_NGINX:-False}
      CANARY_WEB_IMAGE_UPLOAD_PATH: ${CANARY_WEB_IMAGE_UPLOAD_PATH:-/uploads}
      CANARY_WG_PRIVATE_KEY_SEED: ${CANARY_WG_PRIVATE_KEY_SEED:-vk/GD+frlhve/hDTTSUvqpQ/WsQtioKAri0Rt5mg7dw=}

      # ERROR_LOG_WEBHOOK: ${ERROR_LOG_WEBHOOK:-}
      LOG_FILE: ${LOG_FILE:-switchboard.log}

    volumes_from:
      - canarytokens-frontend
    ports:
      - "25:2500"
      - "3306:3306"
      - "53:5354"
      - "53:5354/udp"
      - "6443:6443"
      - "8083:8083"
      - "51820:51820/udp"

volumes:
  logs:
  uploads:
```

**Additional context**

*le sigh*

**Comment by nvroot** [comment]
Looks great! You can also use anchors to avoid writing the same configuration twice.

```
x-shared-env: &shared-env
  CANARY_ALERT_EMAIL_FROM_ADDRESS: ${CANARY_ALERT_EMAIL_FROM_ADDRESS:-do-not-reply@your.domain.tld}
  CANARY_ALERT_EMAIL_FROM_DISPLAY: ${CANARY_ALERT_EMAIL_FROM_DISPLAY:-Canary Tokens}
  CANARY_ALERT_EMAIL_SUBJECT: ${CANARY_ALERT_EMAIL_SUBJECT:-Canary Token Triggered}
  CANARY_DOMAINS: ${CANARY_DOMAINS:-localhost,127.0.0.1}
  CANARY_FORCE_HTTPS: ${CANARY_FORCE_HTTPS:-False}
  CANARY_FRONTEND_LOG_COUNT: ${CANARY_FRONTEND_LOG_COUNT:-10}
  CANARY_FRONTEND_LOG_SIZE: ${CANARY_FRONTEND_LOG_SIZE:-10485760}
  # CANARY_GOOGLE_API_KEY: ${CANARY_GOOGLE_API_KEY:-} 
  # CANARY_IPINFO_API_KEY: ${CANARY_IPINFO_API_KEY:-}
  # CANARY_MAILGUN_API_KEY: ${CANARY_MAILGUN_API_KEY:-}
  # CANARY_MAILGUN_DOMAIN_NAME: ${CANARY_MAILGUN_DOMAIN_NAME:-}
  # CANARY_MANDRILL_API_KEY: ${CANARY_MANDRILL_API_KEY:-}
  CANARY_MAX_ALERTS_PER_MINUTE: ${CANARY_MAX_ALERTS_PER_MINUTE:-1000}
  CANARY_MAX_UPLOAD_SIZE: ${CANARY_MAX_UPLOAD_SIZE:-10485760}
  CANARY_NXDOMAINS: ${CANARY_NXDOMAINS:-nx.127.0.0.1,nx.localhost}
  CANARY_PUBLIC_DOMAIN: ${CANARY_PUBLIC_DOMAIN:-canarytokens.localhost}
  CANARY_PUBLIC_IP: ${CANARY_PUBLIC_IP:-127.0.0.1}
  CANARY_REAL_IP_HEADER: ${CANARY_REAL_IP_HEADER:-x-real-ip}
  CANARY_REDIS_DB: ${CANARY_REDIS_DB:-0}
  CANARY_REDIS_HOST: ${CANARY_REDIS_HOST:-redis}
  CANARY_REDIS_PORT: ${CANARY_REDIS_PORT:-6379}
  CANARY_SENDGRID_API_KEY: ${CANARY_SENDGRID_API_KEY:-CHANGE_ME}
  CANARY_SENDGRID_SANDBOX_MODE: ${CANARY_SENDGRID_SANDBOX_MODE:-True}
  # CANARY_SENTRY_DSN: ${CANARY_SENTRY_DSN:-}
  # CANARY_SENTRY_ENABLE: ${CANARY_SENTRY_ENABLE:-False}
  # CANARY_SENTRY_ENVIRONMENT: ${CANARY_SENTRY_ENVIRONMENT:-local}
  # CANARY_SMTP_PASSWORD: ${CANARY_SMTP_PASSWORD:-}
  # CANARY_SMTP_PORT: ${CANARY_SMTP_PORT:-}
  # CANARY_SMTP_SERVER: ${CANARY_SMTP_SERVER:-}
  # CANARY_SMTP_USERNAME: ${CANARY_SMTP_USERNAME:-}
  CANARY_SWITCHBOARD_LOG_COUNT: ${CANARY_SWITCHBOARD_LOG_COUNT:-20}
  CANARY_SWITCHBOARD_LOG_SIZE: ${CANARY_SWITCHBOARD_LOG_SIZE:-500000000}
  CANARY_SWITCHBOARD_SCHEME: ${CANARY_SWITCHBOARD_SCHEME:-http}
  CANARY_TOKEN_RETURN: ${CANARY_TOKEN_RETURN:-gif}
  CANARY_USING_NGINX: ${CANARY_USING_NGINX:-False}
  CANARY_WEB_IMAGE_UPLOAD_PATH: ${CANARY_WEB_IMAGE_UPLOAD_PATH:-/uploads}
  CANARY_WG_PRIVATE_KEY_SEED: ${CANARY_WG_PRIVATE_KEY_SEED:-vk/GD+frlhve/hDTTSUvqpQ/WsQtioKAri0Rt5mg7dw=}
  # ERROR_LOG_WEBHOOK: ${ERROR_LOG_WEBHOOK:-}
services:
  canarytokens-frontend:
    image: thinkst/canarytokens:latest
    command: bash -c "cd frontend; env | grep ^CANARY_ > ../frontend/frontend.env; cp ../frontend/frontend.env ../switchboard/switchboard.env; poetry run python -m uvicorn app:app --host 0.0.0.0 --port 8082"
    restart: unless-stopped
    environment:
      <<: *shared-env
      LOG_FILE: ${LOG_FILE:-frontend.log}
    volumes:
      - logs:/logs
      - uploads:/uploads
    ports:
     - "8082:8082"

  canarytokens-switchboard:
    image: thinkst/canarytokens:latest
    command: bash -c "cd switchboard; rm -f switchboard.pid; env | grep ^CANARY_ > ../frontend/frontend.env; cp ../frontend/frontend.env ../switchboard/switchboard.env; poetry run twistd -noy switchboard.tac --pidfile=switchboard.pid"
    restart: unless-stopped
    environment:
      <<: *shared-env
      LOG_FILE: ${LOG_FILE:-switchboard.log}
    volumes_from:
      - canarytokens-frontend
    ports:
      - "25:2500"
      - "3306:3306"
      - "53:5354"
      - "53:5354/udp"
      - "6443:6443"
      - "8083:8083"
      - "51820:51820/udp"

volumes:
  logs:
  uploads:
```
